site_name: openshift-ppc64le
theme:
  name: mkdocs
  nav_style: dark
  navigation_depth: 3
  favicon: img/favicon.ico
nav:
  - Home(grown): index.md
  - Contribute: contrib.md
  - External: actually-helped.md
copyright: Â© Copyright IBM Corp. 2020